name: icalepcs-2019-jupyterlab
channels:
  - conda-forge
dependencies:
  - jupyterlab=1.1.4
  - ipympl
  ##
  # jupyterlab-demo
  ##
  - nodejs=11
  - nbconvert=5.5
  # Python Kernel
  - ipywidgets=7.5.1
  - ipyleaflet=0.11.2
  - altair=3.2.0
  - bqplot=0.11.8
  - dask=2.5
  - matplotlib=3.1.1
  - pandas=0.25.0
  - python=3.7
  - scikit-image=0.15.0
  - scikit-learn=0.21
  - seaborn=0.9
  - tensorflow=1.13
  - sympy=1.4
  - pyyaml
  - traittypes==0.2.1
  - invoke=1.2
  # C++ Kernel
  - xeus-cling=0.6
  - xtensor=0.20.8
  - xtensor-blas=0.16.1
  - xwidgets=0.18.0
  - xleaflet=0.9.0
  # R Kernel
  - r-ggplot2
  - r-irkernel=1.0

  ##
  # hdf5-examples
  ##
  - pip
  - pip:
    - ./jupyterlab-hdf5
    - awscli==1.16.250
    - h5py==2.10.0
    - h5glance==0.6
    - karabo_data==0.6.2
    - fastapi
    - uvicorn
    - cookiecutter
